"""Terraform and Bicep IaC generator from Cloud Topology Diagram.

Takes the CTD output (landing zones, VNets, subnets, resources, dependencies)
and produces deployment-ready Terraform modules or Bicep templates following
CAF naming conventions.
"""

from __future__ import annotations

import re
from datetime import datetime, timezone
from typing import Any


# ---------------------------------------------------------------------------
# CAF Naming helpers
# ---------------------------------------------------------------------------

def _sanitize(name: str) -> str:
    """Lowercase, replace non-alphanum with hyphens, strip edges."""
    return re.sub(r"[^a-z0-9-]", "-", name.lower()).strip("-")[:60]


def _caf_name(resource_type: str, workload: str, env: str, region: str, instance: int = 1) -> str:
    abbrev = {
        "resource_group": "rg", "virtual_network": "vnet", "subnet": "snet",
        "network_security_group": "nsg", "public_ip": "pip", "nic": "nic",
        "vm": "vm", "disk": "disk", "bastion": "bas", "firewall": "afw",
        "load_balancer": "lbi", "vpn_gateway": "vpng", "route_table": "rt",
    }
    prefix = abbrev.get(resource_type, resource_type[:4])
    return f"{prefix}-{_sanitize(workload)}-{_sanitize(env)}-{_sanitize(region)}-{instance:03d}"


# ═══════════════════════════════════════════════════════════════════════════
#  Terraform Generator
# ═══════════════════════════════════════════════════════════════════════════

def generate_terraform(
    topology: dict[str, Any],
    region: str = "eastus",
    naming_prefix: str = "migrate",
    environment: str = "prod",
    backend: str = "local",
    include_tags: bool = True,
) -> dict[str, str]:
    """Generate Terraform files from a cloud topology.

    Returns a dict of {filepath: content} ready to be zipped/downloaded.
    """
    files: dict[str, str] = {}

    containers = topology.get("containers", [])
    nodes = topology.get("nodes", [])
    edges = topology.get("edges", [])
    optional = topology.get("optional_components", [])

    lzs = [c for c in containers if c.get("type") == "landing_zone"]
    vnets = [c for c in containers if c.get("type") == "vnet"]
    subnets = [c for c in containers if c.get("type") == "subnet"]

    # --- main.tf ---
    main_lines = [
        f'# Auto-generated by Azure Migrate Simulations — {datetime.now(timezone.utc).isoformat()}',
        f'# Region: {region} | Prefix: {naming_prefix} | Environment: {environment}',
        '',
        'terraform {',
        '  required_version = ">= 1.5.0"',
        '  required_providers {',
        '    azurerm = {',
        '      source  = "hashicorp/azurerm"',
        '      version = "~> 3.80"',
        '    }',
        '  }',
    ]
    if backend == "azurerm":
        main_lines += [
            '  backend "azurerm" {',
            f'    resource_group_name  = "rg-tfstate-{_sanitize(naming_prefix)}"',
            f'    storage_account_name = "st{_sanitize(naming_prefix).replace("-","")}tfstate"',
            f'    container_name       = "tfstate"',
            f'    key                  = "{_sanitize(naming_prefix)}-{environment}.tfstate"',
            '  }',
        ]
    main_lines += [
        '}',
        '',
        'provider "azurerm" {',
        '  features {}',
        '}',
        '',
        '# --- Resource Groups ---',
    ]

    # One RG per landing zone
    for lz in lzs:
        rg_name = _caf_name("resource_group", naming_prefix, _lz_env(lz), region)
        tf_id = _tf_id(lz["id"])
        main_lines += [
            f'resource "azurerm_resource_group" "{tf_id}" {{',
            f'  name     = "{rg_name}"',
            f'  location = var.region',
            '',
        ]
        if include_tags:
            main_lines += [
                '  tags = merge(var.common_tags, {',
                f'    LandingZone = "{lz["label"]}"',
                '  })',
            ]
        main_lines += ['}', '']

    # VNets
    main_lines.append('# --- Virtual Networks ---')
    for vnet in vnets:
        parent_lz = _find_parent_lz(vnet, containers)
        rg_ref = f'azurerm_resource_group.{_tf_id(parent_lz)}.name' if parent_lz else f'"rg-{naming_prefix}"'
        vnet_name = _caf_name("virtual_network", naming_prefix, _lz_env_from_id(vnet.get("parent", "")), region)
        cidr = _extract_cidr(vnet.get("label", ""))
        tf_id = _tf_id(vnet["id"])
        main_lines += [
            f'resource "azurerm_virtual_network" "{tf_id}" {{',
            f'  name                = "{vnet_name}"',
            f'  location            = var.region',
            f'  resource_group_name = {rg_ref}',
            f'  address_space       = ["{cidr}"]',
            '',
        ]
        if include_tags:
            main_lines.append('  tags = var.common_tags')
        main_lines += ['}', '']

    # Subnets
    main_lines.append('# --- Subnets ---')
    for sn in subnets:
        parent_vnet = sn.get("parent", "")
        sn_name = _caf_name("subnet", _sanitize(sn.get("label", "").split("(")[0].strip()), _lz_env_from_id(parent_vnet), region)
        cidr = _extract_cidr(sn.get("label", ""))
        tf_id = _tf_id(sn["id"])
        vnet_tf = _tf_id(parent_vnet)
        parent_lz = _find_parent_lz_for_vnet(parent_vnet, containers)
        rg_ref = f'azurerm_resource_group.{_tf_id(parent_lz)}.name' if parent_lz else f'"rg-{naming_prefix}"'
        main_lines += [
            f'resource "azurerm_subnet" "{tf_id}" {{',
            f'  name                 = "{sn_name}"',
            f'  resource_group_name  = {rg_ref}',
            f'  virtual_network_name = azurerm_virtual_network.{vnet_tf}.name',
            f'  address_prefixes     = ["{cidr}"]',
            '}',
            '',
        ]

    # NSG per subnet
    main_lines.append('# --- Network Security Groups ---')
    for sn in subnets:
        nsg_name = _caf_name("network_security_group", _sanitize(sn.get("label", "").split("(")[0].strip()), "prod", region)
        tf_id_nsg = _tf_id(sn["id"]) + "_nsg"
        parent_vnet = sn.get("parent", "")
        parent_lz = _find_parent_lz_for_vnet(parent_vnet, containers)
        rg_ref = f'azurerm_resource_group.{_tf_id(parent_lz)}.name' if parent_lz else f'"rg-{naming_prefix}"'
        main_lines += [
            f'resource "azurerm_network_security_group" "{tf_id_nsg}" {{',
            f'  name                = "{nsg_name}"',
            f'  location            = var.region',
            f'  resource_group_name = {rg_ref}',
            '',
        ]
        if include_tags:
            main_lines.append('  tags = var.common_tags')
        main_lines += ['}', '']

    # VMs
    main_lines.append('# --- Virtual Machines ---')
    for node in nodes:
        if node.get("resource_type") not in ("vm", "paas"):
            continue
        vm_name = _sanitize(node.get("source_vm", node.get("label", "vm")))[:15]
        sku = node.get("azure_sku", "Standard_B2s")
        is_windows = "windows" in node.get("title", "").lower() or "windows" in node.get("label", "").lower()
        resource_type = "azurerm_windows_virtual_machine" if is_windows else "azurerm_linux_virtual_machine"
        tf_id = _tf_id(node["id"])

        # Find which subnet this node is in
        sn_id = node.get("container", "")
        sn_tf = _tf_id(sn_id) if sn_id else "snet_general"
        parent_vnet = _find_parent_of(sn_id, containers)
        parent_lz = _find_parent_lz_for_vnet(parent_vnet, containers)
        rg_ref = f'azurerm_resource_group.{_tf_id(parent_lz)}.name' if parent_lz else f'"rg-{naming_prefix}"'

        main_lines += [
            f'resource "{resource_type}" "{tf_id}" {{',
            f'  name                  = "{vm_name}"',
            f'  location              = var.region',
            f'  resource_group_name   = {rg_ref}',
            f'  size                  = "{sku}"',
            f'  admin_username        = var.admin_username',
            f'  network_interface_ids = [azurerm_network_interface.{tf_id}_nic.id]',
            '',
        ]
        if is_windows:
            main_lines.append('  admin_password = var.admin_password')
        else:
            main_lines += [
                '  admin_ssh_key {',
                '    username   = var.admin_username',
                '    public_key = var.ssh_public_key',
                '  }',
            ]
        main_lines += [
            '',
            '  os_disk {',
            '    caching              = "ReadWrite"',
            '    storage_account_type = "Premium_LRS"',
            '  }',
            '',
            f'  source_image_reference {{',
            f'    publisher = "{("MicrosoftWindowsServer" if is_windows else "Canonical")}"',
            f'    offer     = "{("WindowsServer" if is_windows else "0001-com-ubuntu-server-jammy")}"',
            f'    sku       = "{("2022-datacenter-g2" if is_windows else "22_04-lts-gen2")}"',
            f'    version   = "latest"',
            '  }',
            '',
        ]
        if include_tags:
            main_lines += [
                '  tags = merge(var.common_tags, {',
                f'    SourceVM      = "{node.get("source_vm", "")}"',
                f'    Readiness     = "{node.get("readiness", "")}"',
                f'    MonthlyCost   = "{node.get("monthly_cost", 0)}"',
                '  })',
            ]
        main_lines += ['}', '']

        # NIC
        main_lines += [
            f'resource "azurerm_network_interface" "{tf_id}_nic" {{',
            f'  name                = "nic-{vm_name}"',
            f'  location            = var.region',
            f'  resource_group_name = {rg_ref}',
            '',
            '  ip_configuration {',
            f'    name                          = "internal"',
            f'    subnet_id                     = azurerm_subnet.{sn_tf}.id',
            f'    private_ip_address_allocation = "Dynamic"',
            '  }',
            '}',
            '',
        ]

    # Optional components
    for opt in optional:
        if not opt.get("enabled"):
            continue
        oid = opt["id"]
        if oid == "azure_firewall":
            main_lines += _tf_firewall(naming_prefix, region, containers, include_tags)
        elif oid == "bastion":
            main_lines += _tf_bastion(naming_prefix, region, containers, include_tags)
        elif oid == "vpn_gateway":
            main_lines += _tf_vpn(naming_prefix, region, containers, include_tags)

    files["main.tf"] = "\n".join(main_lines)

    # --- variables.tf ---
    files["variables.tf"] = f"""# Variables for {naming_prefix} migration
variable "region" {{
  type    = string
  default = "{region}"
}}

variable "admin_username" {{
  type    = string
  default = "azureadmin"
}}

variable "admin_password" {{
  type      = string
  sensitive = true
  default   = ""
}}

variable "ssh_public_key" {{
  type    = string
  default = ""
}}

variable "common_tags" {{
  type = map(string)
  default = {{
    Environment = "{environment}"
    ManagedBy   = "AzureMigrateSimulations"
    Project     = "{naming_prefix}"
  }}
}}
"""

    # --- outputs.tf ---
    rg_outputs = []
    for lz in lzs:
        tf_id = _tf_id(lz["id"])
        rg_outputs.append(f'output "{tf_id}_rg_id" {{\n  value = azurerm_resource_group.{tf_id}.id\n}}')
    files["outputs.tf"] = f"# Outputs\n\n" + "\n\n".join(rg_outputs) + "\n"

    # --- terraform.tfvars.example ---
    files["terraform.tfvars.example"] = f"""region         = "{region}"
admin_username = "azureadmin"
# admin_password = "ChangeMe!123"  # For Windows VMs
# ssh_public_key = "ssh-rsa AAAA..."  # For Linux VMs
"""

    return files


# ═══════════════════════════════════════════════════════════════════════════
#  Bicep Generator
# ═══════════════════════════════════════════════════════════════════════════

def generate_bicep(
    topology: dict[str, Any],
    region: str = "eastus",
    naming_prefix: str = "migrate",
    environment: str = "prod",
    include_tags: bool = True,
) -> dict[str, str]:
    """Generate Bicep files from a cloud topology.

    Returns a dict of {filepath: content}.
    """
    files: dict[str, str] = {}

    containers = topology.get("containers", [])
    nodes = topology.get("nodes", [])
    optional = topology.get("optional_components", [])

    lzs = [c for c in containers if c.get("type") == "landing_zone"]
    vnets = [c for c in containers if c.get("type") == "vnet"]
    subnets = [c for c in containers if c.get("type") == "subnet"]

    lines = [
        f'// Auto-generated by Azure Migrate Simulations — {datetime.now(timezone.utc).isoformat()}',
        f'// Region: {region} | Prefix: {naming_prefix} | Environment: {environment}',
        '',
        'targetScope = \'subscription\'',
        '',
        f'param location string = \'{region}\'',
        f'param environment string = \'{environment}\'',
        f'param namingPrefix string = \'{naming_prefix}\'',
        'param adminUsername string = \'azureadmin\'',
        '@secure()',
        'param adminPassword string = \'\'',
        '',
        'var commonTags = {',
        f'  Environment: environment',
        f'  ManagedBy: \'AzureMigrateSimulations\'',
        f'  Project: namingPrefix',
        '}',
        '',
    ]

    # Resource Groups
    lines.append('// --- Resource Groups ---')
    for lz in lzs:
        rg_name = _caf_name("resource_group", naming_prefix, _lz_env(lz), region)
        bicep_id = _bicep_id(lz["id"])
        lines += [
            f'resource {bicep_id} \'Microsoft.Resources/resourceGroups@2023-07-01\' = {{',
            f'  name: \'{rg_name}\'',
            f'  location: location',
            f'  tags: commonTags',
            '}',
            '',
        ]

    # Module for VNets + Subnets + VMs (deployed at RG scope)
    for lz in lzs:
        lz_vnets = [v for v in vnets if v.get("parent") == lz["id"]]
        if not lz_vnets:
            continue
        bicep_rg = _bicep_id(lz["id"])
        mod_name = _bicep_id(lz["id"]) + "Deploy"
        lines += [
            f'module {mod_name} \'./modules/landingZone.bicep\' = {{',
            f'  name: \'{mod_name}\'',
            f'  scope: {bicep_rg}',
            '  params: {',
            f'    location: location',
            f'    namingPrefix: namingPrefix',
            f'    environment: environment',
            f'    adminUsername: adminUsername',
            f'    adminPassword: adminPassword',
            f'    tags: commonTags',
            '  }',
            '}',
            '',
        ]

    files["main.bicep"] = "\n".join(lines)

    # --- modules/landingZone.bicep ---
    mod_lines = [
        '// Landing Zone module — deploys VNet, subnets, NSGs, VMs',
        '',
        'param location string',
        'param namingPrefix string',
        'param environment string',
        'param adminUsername string',
        '@secure()',
        'param adminPassword string',
        'param tags object',
        '',
    ]

    # Generate one VNet + subnets + VMs for the prod landing zone
    prod_vnets = [v for v in vnets if "prod" in v.get("parent", "").lower() or "app" in v.get("parent", "").lower()]
    if prod_vnets:
        vnet = prod_vnets[0]
        cidr = _extract_cidr(vnet.get("label", ""))
        vnet_name = '${namingPrefix}-vnet-${environment}'
        mod_lines += [
            f'resource vnet \'Microsoft.Network/virtualNetworks@2023-05-01\' = {{',
            f'  name: \'{vnet_name}\'',
            f'  location: location',
            f'  tags: tags',
            '  properties: {',
            '    addressSpace: {',
            f'      addressPrefixes: [\'{cidr}\']',
            '    }',
            '    subnets: [',
        ]
        prod_subnets = [s for s in subnets if s.get("parent") == vnet["id"]]
        for sn in prod_subnets:
            sn_cidr = _extract_cidr(sn.get("label", ""))
            sn_label = _sanitize(sn.get("label", "").split("(")[0].strip())
            mod_lines += [
                '      {',
                f'        name: \'snet-{sn_label}\'',
                '        properties: {',
                f'          addressPrefix: \'{sn_cidr}\'',
                '        }',
                '      }',
            ]
        mod_lines += ['    ]', '  }', '}', '']

    # VMs
    vm_nodes = [n for n in nodes if n.get("resource_type") == "vm"]
    for i, node in enumerate(vm_nodes[:50]):  # Cap for readability
        vm_name = _sanitize(node.get("source_vm", f"vm{i}"))[:15]
        sku = node.get("azure_sku", "Standard_B2s")
        is_win = "windows" in node.get("title", "").lower()
        mod_lines += [
            f'resource vm{i} \'Microsoft.Compute/virtualMachines@2023-07-01\' = {{',
            f'  name: \'{vm_name}\'',
            f'  location: location',
            f'  tags: union(tags, {{ SourceVM: \'{node.get("source_vm", "")}\' }})',
            '  properties: {',
            '    hardwareProfile: {',
            f'      vmSize: \'{sku}\'',
            '    }',
            '    osProfile: {',
            f'      computerName: \'{vm_name[:15]}\'',
            f'      adminUsername: adminUsername',
            f'      adminPassword: adminPassword',
            '    }',
            '    storageProfile: {',
            '      osDisk: {',
            '        createOption: \'FromImage\'',
            '        managedDisk: { storageAccountType: \'Premium_LRS\' }',
            '      }',
            '      imageReference: {',
            f'        publisher: \'{("MicrosoftWindowsServer" if is_win else "Canonical")}\'',
            f'        offer: \'{("WindowsServer" if is_win else "0001-com-ubuntu-server-jammy")}\'',
            f'        sku: \'{("2022-datacenter-g2" if is_win else "22_04-lts-gen2")}\'',
            '        version: \'latest\'',
            '      }',
            '    }',
            '  }',
            '}',
            '',
        ]

    files["modules/landingZone.bicep"] = "\n".join(mod_lines)

    # --- parameters.json ---
    files["parameters.json"] = f"""{{"$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {{
    "location": {{ "value": "{region}" }},
    "environment": {{ "value": "{environment}" }},
    "namingPrefix": {{ "value": "{naming_prefix}" }},
    "adminUsername": {{ "value": "azureadmin" }}
  }}
}}
"""

    return files


# ═══════════════════════════════════════════════════════════════════════════
#  Internal helpers
# ═══════════════════════════════════════════════════════════════════════════

def _tf_id(raw_id: str) -> str:
    return re.sub(r"[^a-zA-Z0-9_]", "_", raw_id)

def _bicep_id(raw_id: str) -> str:
    return re.sub(r"[^a-zA-Z0-9]", "", raw_id)

def _lz_env(lz: dict) -> str:
    label = lz.get("label", "").lower()
    if "dev" in label or "test" in label:
        return "devtest"
    if "connectivity" in label:
        return "conn"
    if "identity" in label:
        return "id"
    if "management" in label:
        return "mgmt"
    return "prod"

def _lz_env_from_id(lz_id: str) -> str:
    if "dev" in lz_id or "test" in lz_id:
        return "devtest"
    if "conn" in lz_id:
        return "conn"
    return "prod"

def _extract_cidr(label: str) -> str:
    m = re.search(r"(\d+\.\d+\.\d+\.\d+/\d+)", label)
    return m.group(1) if m else "10.0.0.0/16"

def _find_parent_lz(container: dict, all_containers: list) -> str | None:
    parent_id = container.get("parent")
    if not parent_id:
        return None
    parent = next((c for c in all_containers if c["id"] == parent_id), None)
    if parent and parent.get("type") == "landing_zone":
        return parent["id"]
    if parent:
        return _find_parent_lz(parent, all_containers)
    return None

def _find_parent_lz_for_vnet(vnet_id: str, all_containers: list) -> str | None:
    vnet = next((c for c in all_containers if c["id"] == vnet_id), None)
    if not vnet:
        return None
    return _find_parent_lz(vnet, all_containers)

def _find_parent_of(child_id: str, all_containers: list) -> str:
    child = next((c for c in all_containers if c["id"] == child_id), None)
    return child.get("parent", "") if child else ""

def _tf_firewall(prefix: str, region: str, containers: list, tags: bool) -> list[str]:
    return [
        f'resource "azurerm_firewall" "hub_firewall" {{',
        f'  name                = "{_caf_name("firewall", prefix, "conn", region)}"',
        f'  location            = var.region',
        f'  resource_group_name = azurerm_resource_group.{_tf_id("lz-connectivity")}.name',
        f'  sku_name            = "AZFW_VNet"',
        f'  sku_tier            = "Standard"',
        '}', '',
    ]

def _tf_bastion(prefix: str, region: str, containers: list, tags: bool) -> list[str]:
    return [
        f'resource "azurerm_bastion_host" "bastion" {{',
        f'  name                = "{_caf_name("bastion", prefix, "conn", region)}"',
        f'  location            = var.region',
        f'  resource_group_name = azurerm_resource_group.{_tf_id("lz-connectivity")}.name',
        '}', '',
    ]

def _tf_vpn(prefix: str, region: str, containers: list, tags: bool) -> list[str]:
    return [
        f'resource "azurerm_virtual_network_gateway" "vpn" {{',
        f'  name                = "{_caf_name("vpn_gateway", prefix, "conn", region)}"',
        f'  location            = var.region',
        f'  resource_group_name = azurerm_resource_group.{_tf_id("lz-connectivity")}.name',
        f'  type                = "Vpn"',
        f'  sku                 = "VpnGw1"',
        '}', '',
    ]
